# Generated by Django 4.0.2 on 2022-04-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.IntegerField(default=10),
        ),
    ]
