# Generated by Django 4.0.2 on 2022-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_pledge_anonymous_remove_project_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='time',
            field=models.IntegerField(default=10),
        ),
    ]
