# Generated by Django 4.0.2 on 2022-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_pledge_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
